:sample-dir: C:\Code\git\dessert\dessert-site\dessert-sample

== Concepts and Terminology

=== Slices

When using dessertj you work most of the time with some `Slice` implementation.
Mostly this is one of:

Slice::
DessertJ is all about slices. A slice is an arbitrary set of .class files.
Clazz::
The `Clazz` is the smallest possible slice. It represents a single .class file.
Classpath::
The `Classpath` is the starting point of every _dessertj_ test and the biggest
possible slice.
*Warning: Never try to combine slices from different Classpath instances!*
Root::
A `Root` is a special slice that represents a .jar file or a classes directory.
ModuleSlice::
A `ModuleSlice` represents the public interface of a module.
For a JPMS module these are all unqualified exports.

The following diagram gives an overview of the implementations provided by dessertj:

[plantuml, slice-overview, svg]
....
include::{sample-dir}/target/docgen/slice-overview.puml[]
....

The most important `Slice` methods are `plus`, `minus`, and `slice` to create new slices from existing
ones. The `AbstractRootSlice` provides some convenience methods to work with packages. `packageOf` returns
a slice of all classes within one package (without sub-packages). `packageTreeOf' returns a slice of
all classes within a package, or a nested sub-package. Called on a `Root` these methods return only
classes within that root. A `Root` is a classes directory or a .jar file that belongs to the `Classpath`.
To get a `Root` you can use the `Classpath` method `rootOf`.

The `Classpath` methods `asClazz` and `sliceOf` can create slices for classes that are not on the
`Classpath` such as classes located in the java or javax packages or dependencies of some classes.
In such a case the `Classpath` uses the current `ClassLoader` to get the corresponding .class file.
If this does not work either, it creates a placeholder `Clazz` that contains only the classname.

The `slice` methods of `Classpath` do not necessarily return a slice that can be resolved to a concrete
set of classes. A slice may also be defined by a name-pattern or some predicate. For such a slice one
can use the `contains` method to check whether a `Clazz` belongs to it, thus the class fulfills
all predicates. But calling `getClazzes` will throw a `ResolveException`. This happens if the
`Classpath` contains none of the classes belonging to the slice. Internally _dessertj_ works with such
predicate based slices as long as `getClazzes` has not been called, for performance reasons.

_DessertJ_ has been optimized to resolve name-pattern very fast. Hence, it's a good practice to first
slice be name (or `packageOf`/`packageTreeOf`) then used predicates to slice-down the slices further.

`getDependencies` returns the dependencies of a slice and `uses` checks whether some other slice
contains one of these dependencies.

To add features to existing slices always extend `AbstractDelegateSlice`. The `named` method returns
one such extension that makes a slices' `toString` method return the name passed.

=== Modules

Dessert's JPMS support can be used through the `ModuleRegistry`.
It's `getModule` method returns the corresponding module by name.
`JavaModules` and `JdkModules` provides pre-defined constants
for the corresponding JDK 17 modules:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/concepts/modules/ModulesTest.java[tags=declaration]
----

The following sample is not very useful, but it shows how to use the module API:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/concepts/modules/ModulesTest.java[tags=junit]
----

A `ModuleSlice` itself contains only the classes exported to anyone.
The `getImplementation` method of a `ModuleSlice` returns all classes of a module, no matter whether
they are exported. The `JpmsModule` method `getExportsTo` returns the classes that are exported
to some certain module.

The module API is fully supported for JDK 8 and earlier. Therefore, dessertj comes with `FixedModule`
definitions which are based on JDK 17. They are used as fall-back if the current JDK does not
provide modules.

_AssertionsKt_ has been excluded, because it adds dependencies to the Kotlin runtime system,
which are not available for Java.

=== Name-Patterns

Name-patterns are the most important means to define slices. A name-pattern
identifies a set of classes by their full qualified classname.

The syntax has been motivated by the
https://www.eclipse.org/aspectj/doc/released/progguide/quick-typePatterns.htmlAspectJ TypeNamePattern]
with slight modifications:

- The pattern can either be a plain type name, the wildcard *, or an
  identifier with embedded * or .. wildcards or the | separator.
- An * matches any sequence of characters, but does not match the package separator ".".
- An | separates alternatives that do not contain a package separator ".".
- An .. matches any sequence of characters that starts and ends with the package separator ".".
- The identifier to match with is always the name returned by {@link Class#getName()}. 
  Thus, $ is the only inner-type separator supported.
- The * does match $, too.
- A leading .. additionally matches the root package.

.Examples:
[cols="1,4"]
|===
|Pattern|Description

|sample.Foo|Matches only sample.Foo
|sample.Foo*|Matches all types in sample starting with "Foo" and all inner-types of Foo
|sample.bar\|baz.*|Matches all types in sample.bar and sample.baz
|sample.Foo$*|Matches only inner-types of Foo
|..Foo|Matches all Foo in any package (incl. root package)
|*.*..Foo|Matches all Foo nested in a sub-package
|*|Matches all types in the root package
|..*|Matches all types
|===

=== Predicates

Predicates are another way to define slices. Typically, they are used to selecting classes
from an existing `Slice` that meets certain properties. `Predicate` is a functional interface.
`Predicates` provides `and`, `or` and `not` to combine predicates. `ClazzPredicates` contains
some pre-defined predicates for classes.

The following code fragment demonstrates their usage:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/concepts/predicates/PredicatesSampleTest.java[tags=predicates]
----

`slicingInterfaces` contains all public interfaces, enums or annotations of the `slicing` package within the
`dessertj-core` library. The assertion checks that the `assertions` packages uses only these types by asserting
that it uses nothing from the complement. That check will fail, because `assertions` uses i.e. `Clazz`.

=== Assertions

All dessertj assertions start with one of the static `SliceAssertions` methods `assertThat`
or its alias `dessert`. These methods return a `SliceAssert` object with its most important
methods `usesNot` and `usesOnly`. Both methods return a `SliceAssert` again, so that assertions
can be queued:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/start/DessertSampleTest.java[tags=queuing]
----

When an assertion fails it throws an `AssertionError`. The message shows details about the cause
of the failure. This message is produced by the `DefaultIllegalDependenciesRenderer`. That renderer
can be replaced with the `SliceAssert` method `renderWith`.

NOTE: To have any effect `renderWith` must be invoked before the assertions (i.e. `usesNot`).

=== Cycle detection

`SliceAssert` provides the method `isCycleFree` to check whether a set of slices has any
cyclic dependencies. Because each `Clazz` is a `Slice` one check the classes of slice
for a cycle like this:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/concepts/cycle/CycleTest.java[tags=classCycle]
----

The sample contains a cycle, hence it produces the following output:

----
include::{sample-dir}/target/docgen/classCycle.txt[]
----

Class-cycles are quite common and should not be a problem as long as the cycle is within a
package. Package-cycles on the other hand are an indicator for serious architecture problems.
To detect these you can use:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/concepts/cycle/CycleTest.java[tags=packageCycle]
----

This produces:

----
include::{sample-dir}/target/docgen/packageCycle.txt[]
----

The `AssertionError` message is produced by the `DefaultCycleRenderer`. Another `CycleRenderer`
can be given with the `SliceAssert` method `renderCycleWith`.

The `partitionByPackage` is a specialized `Slice` method that partitions the classes of a Slice
by package-name. Thus, it produces a Map for which the package-name is the key, and the value is
a slice containing all classes that belong to the package. In this case the value is a specialized
slice that gives access to the package-name and the parent-package.

The more general `partitionBy` uses a `SlicePartitioner` that maps each class to some key.
The result is a map of `PartitionSlice`. A `PartitionSlice` is a `ConcreteSlice` (set of classes),
with the key assigned. See `SlicePartitioners` for examples of pre-defined slice partitioners.
There is another `partitionBy` method with a second `PartitionSliceFactory`
parameter. This can be used to create specialized `PartitionSlice` objects like the `PackageSlice`.

=== Architecture verification

`SliceAssert` has two additional convenience methods to verify a layered architecture. Therefore,
you have to pass a list of layers to the `dessert` method. `isLayeredStrict` check whether each
layer depends only on classes within itself or classes within its immediate successor.
`isLayeredRelaxed` relaxes this from an _immediate successor_ to _any successor.
The following example shows how to use this:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/concepts/arch/ArchitectureTest.java[tags=arch]
----

=== Class resolving

The `Classpath` needs a `ClassResolver` to find the classes it operates on. By default, the
Classpath uses a resolver that operates on the path defined by the _java.class.path_
system property. You can define your own ClassResolver and add the classes directories and
jar files you want. You can even define your own `ClassRoot` with some custom strategy to
find classes. Then pass that ClassResolver to the Classpath constructor. This will _freeze_
the ClassResolver. Thus, after a ClassResolver is used by a Classpath it, it must not
be changed.

=== Duplicates

The `Classpath` has a method `duplicates` that returns a special `Slice` of all .class files that appear
at least twice on the `Classpath`. Other as the `ClassLoader` _dessert_ does not stop at the first
class that matches a certain name. It always considers all matches. Duplicates are a common cause
of problems, because the implementation is chosen more ore less randomly.

The following code fragment demonstrates this:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/concepts/duplicates/DuplicatesTest.java[tags=duplicates]
----

The sample uses JUnit 5 which has a _module-info.class_ in each of its jars, thus `duplicates` is
not empty. The `Classpath` method `asClazz` returns a single `Clazz` object which represents one
if these module-info classes. A `Clazz` object always represents one single .class file.
`getAlternatives()` returns all classes with the name on the `Classpath`. After subtracting the
module-info classes there are no more duplicates left. An alternative way to get a slice of
all module-info classes is `slice("module-info")` or simple by using the short-cut
`minus("module-info")`, because it filters by name.
