:sample-dir: C:\Code\git\dessert\dessert-site\dessert-sample

[[getting_started]]
== Getting Started

=== Maven Dependency

Add the _dessert-core_ dependency to your project:

[source, xml, indent=0, subs=attributes+]
----
        <dependency>
            <groupId>de.spricom.dessert</groupId>
            <artifactId>dessert-core</artifactId>
            <version>{release-version}</version>
            <scope>test</scope>
        </dependency>
----

=== Snapshot Dependency (optional alternative)

To try out the most current snapshot use:

[source, xml, indent=0]
----
include::{sample-dir}/pom.xml[tags=dep]
----

Snapshot releases require the _OSSRH Snapshot Repository_>:

[source, xml, indent=0]
----
include::{sample-dir}/pom.xml[tags=repo]
----

=== First Test

Implement your first dependency test:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/start/DessertSampleTest.java[tags=fails]
----

Each _dessert_ test starts with the `Classpath`. `Classpath`, `Clazz` and `Root` all implement
the `Slice` interface. Imagine the `Classpath` to be a cake that has to be sliced down to
suitable pieces. The `Clazz` is the smallest possible piece, it represents a single .class file.
A `Root` is a classes directory, a .jar file or a JDK module. `SliceAssertion` provides a
static `assertThatSlice` method to check for unwanted dependencies between slices.

The test above will fail, because it has a dependency to the junit-jupiter-api.jar. Thus, it
produces the following output:

----
include::{sample-dir}/target/docgen/willFail.txt[]
----

The following test shows some other methods to get slices from the `Classpath`:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/start/DessertSampleTest.java[tags=succeeds]
----

The _java..*_ slice represents all classes in the `java` package or any nested package.
The methods `plus` and `minus` can be used do create new slices from existing slices.
The most important methods for slice assertions are `doesNotUse` and `usesOnly`.
Both accept more than one slice.

=== First Modules Test

With dessert projects can profit form the Java Platform Module System (JPMS), even
if they don't use modules. Therefore, dessert provides an easy and intuitive module API:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/intro/ModulesSampleTest.java[]
----

Through the `ModuleRegistry` modules can be accessed by name. `JavaModules` provides
constants for all _java_ modules as of JDK 17. Both are available even for JDK 8 and
earlier. The `usesOnly` assertion makes sure only exported packages
are used from the modules listed.