:sample-dir: C:\Code\git\dessert\dessert-site\dessert-sample
:duplicates-sample-dir: C:\Code\git\dessert\dessert-site\dessert-duplicates-sample
:icons: font

== Practical Guide

=== Motivation

Keeping an architecture clean pays out manifold over time, but it has no immediate business value.
For developers architecture requirements are an additional burden. If you point out an architecture
problem, you will get answers like: "I'll do that later, first it must be working to show it
up to the customer." Actually it's the same with tests, but tests can be written afterwards.
If you point out the same architecture issue after it's working you get answers like:
"Well, it's working and the customer tested it. Never change a running system."
That's why any architecture degrades over time. To get around this, you have to
establish an architecture awareness across your team.

As I pointed out, communicating architecture requirements won't help. Especially inexperienced
developers will focus on other things first. Tools like SonarQube won't help much, either.
Typically, the sonar issues are the last task during a development phase. This is
adding javadoc comments, making some variables final or something like that.
But in that phase no developer will dare to resolve a package cycle, because such a
fundamental change may break the system and needs thorough re-testing.

The _dessert_ library has proved to solve this problem. It's simple and intuitive syntax
can be read by any developer. Thus, it's an easy way to communicate an architecture
requirement. Any violation of such a requirement will break the build on your CI system,
because the corresponding _dessert_ test will fail. Hence, the nose of the
responsible developer will directly be pointed to the corresponding requirement.
Now, the only thing you need, is a plausible comment that explains why it is
important to adhere to that requirement. Over time this will build up
architecture awareness across your team.

=== Sample Code

The code fragments below are excerpts of executable unit tests. See the
https://github.com/hajo70/dessert-site/tree/main/dessert-sample/src/test/java/de/spricom/dessert/guide[dessert-site] project for the full source code.

=== Detecting unwanted dependencies

Developers tend to use everything, simply because it's there, and it looks promising to accomplish
some task. Thus, anything which happens to be available on the class-path can be used for any purpose
in any place. If the software is working and the customers are happy, so what is the problem?
Well, some reasons for more restrictions might be:

- Internal APIs are subject to change without notice. Using internal APIs
may cause trouble when a dependency is updated.
- If you know that some library or API will be replaced by something else, or you
want to get rid of some dependency then you surely don't want that new code
uses that library.
- If you have a big monolith and want to break it down into smaller modules,
then you must reduce the dependencies that hinder you and prevent developers
to introduce additional obstacles.
- You might want to enforce a clean architecture where certain packages or
classes following some naming convention have certain responsibilities.
For example your JPA persistence layer should not use JDBC directly
or your DTOs should not access the file system.
- You want to make sure, some critical code does not use anything that
may cause security vulnerabilities.

Detecting unwanted dependencies using _dessert_ is as simple as:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DetectingUnwantedDependenciesTest.java[tags=doesNotUse]
----

Every developer should be able to read and understand this.
Because it's within a unit-test it is checked during each CI build,
and it can't be ignored.

The _something_ and the _unwanted_ each are a `Slice`. In _dessert_ almost
everything is a `Slice` and you have many ways to tell what's in a
certain slice.

The starting-point for each `Slice` is the `Classpath`:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DetectingUnwantedDependenciesTest.java[tags=cp]
----

NOTE: The `Classpath` is a `Slice`, too.

The _something_ is a part of your handwritten code:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DetectingUnwantedDependenciesTest.java[tags=slices]
----

The _unwanted_ might be something like:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DetectingUnwantedDependenciesTest.java[tags=unwanted]
----

The _something_ and the _unwanted_ examples all specify a 'Slice'. Each of them
can be use in the `assertThatSlice` or in the `doesNotUse` part of the assertion.

=== Enforcing architecture requirements

When defining an architecture you don't specify which dependencies your building blocks must
not use, you rather define the dependencies they do have. With _dessert_ you express
this with the `usesOnly` assertion:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/EnforcingArchitectureTest.java[tags=syntax]
----

Of course, `block`, `dep1` and `dep2` are slices. Within the `usesOnly` all dependencies
that `block` has, must be listed. Usually there are many common dependencies like Java SE
classes, logging API's or standard libraries used everywhere in your application.
For this purpose you can define an instance variable that you can use all over your
architecture test:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/EnforcingArchitectureTest.java[tags=common]
----

It's good practice to have instances variables for all of your main building blocks and
dependencies. Then you can have a test method for each build block, that lists all the
dependencies it is allowed to have. Some of these dependencies are other building blocks, of course.

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/EnforcingArchitectureTest.java[tags=blocks]
----

NOTE: `Slice` instances are immutable.

If you have several classes for architecture tests you may want to define your main
building blocks in a separate class:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/BuildingBlocks.java[tags=code]
----

IMPORTANT: All slices used for an assertion must stem from the same `Classpath` instance.

=== Utilize JPMS information

Libraries implemented with the Java Platform Module System (JPMS) explicitly list the
exported packages. These packages form the public API of a library. Every thing else
is internal and subject to change without notice. Hence, you want to ensure
your building blocks use only the public API. One way to achieve this, is
using the JPMS for your project. But the JPMS is a bit cumbersome especially when
it comes to testing. Therefore, it's not that wide-spread.

With _dessert_ you can profit from the JPMS even if you are not using it for your
project. You still can make sure that your building blocks use only exported packages.
To access module information you need a
https://dessert.spricom.de/apidocs/index.html?de/spricom/dessert/modules/ModuleRegistry.html[ModuleRegistry]:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/JpmsTest.java[tags=jpms]
----

The https://dessert.spricom.de/apidocs/index.html?de/spricom/dessert/modules/fixed/JavaModules.html[JavaModules]
and https://dessert.spricom.de/apidocs/index.html?de/spricom/dessert/modules/fixed/JdkModules.html[JdkModules]
define constants for the modules of the _Java Platform, Standard Edition (Java SE)_ and
the _Java Development Kit (JDK)_ respectively. To ensure some building block uses only the exported
packages of certain Java SE modules, you simply write:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/JpmsTest.java[tags=using]
----

Any other module can be accessed by name from the `ModuleRegistry`:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/JpmsTest.java[tags=module]
----

If you want to make sure the internal API of a module is not used, then
use an assertion like:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/JpmsTest.java[tags=usesNot]
----

NOTE: Dessert's module features are available for older Java versions, too.
This may be useful to prepare for an update to a later Java version.

=== More details about defining slices

The slice operations can be used to create new slices from existing ones:

[cols="a,1"]
|===
|Operation|Description

|
[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=union]
----
|The resulting slice contains all classes from _slice1_ and all classes from _sice2_.
An alternative to get the union of slices is the `Slices.of` method.

|
[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=intersection]
----
|The resulting slice contains only the classes found in both slices.

|
[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=difference]
----
|The resulting slice contains the classes of _slice1_ that don't belong to _slice2_.
|===

The slice operations don't modify the original slices.

The `slice` and the `minus` methods have variants that accept patterns or predicates:

[source, java, indent=0]
.Patterns
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=patterns]
----

NOTE: Patterns are case-sensitive.

[source, java, indent=0]
.Predicates
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=predicates]
----

NOTE: Dessert has been optimized for patterns. Evaluation predicates can be slow.
Thus, predicates should be always the last thing to filter with.

This is the implementation used above to find classes that could not be loaded:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=nodef]
----

To debug predicates it is very useful to see, what is in a slice. Hence, a method like
this is very useful:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=dump]
----

Some libraries use annotations to mark internal or experimental code.
For example
https://junit.org/junit5/docs/current/user-guide/[JUnit 5]
uses https://github.com/apiguardian-team/apiguardian[@API Guardian]
for that purpose. Therefore, dessert provides the
https://dessert.spricom.de/apidocs/index.html?de/spricom/dessert/util/AnnotationPattern.html[AnnotationPattern]:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DefiningSlicesTest.java[tags=annotations]
----

NOTE: Dessert recognizes annotations for retention policy `RUNTIME` and `CLASS`.

=== Detecting cycles

The problem with a cycle is, it does not have a beginning nor does it have an end. Thus, if you
pick out any class involved in a dependency cycle you cannot use it without all other classes involved
in that cycle. This is not a concern for small cycles of closely related classes, but it's a
nightmare if you have to change a software with big intertwined cycles.

Dessert can detect cycles between any set of slices (remember: a `Clazz` is a `Slice`, too).
Sometimes it's hard and unnecessary to prevent class cycles, but package-cycles are a clear
indicator for design flaws. There is always a clean design without package-cycles.
Use the following code to assert that some building block `block` has no package-cycle:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=cycle]
----

Typically, it's necessary to move classes to resolve a cycle. To be backwards compatible
a deprecated place-holder must be kept in the old place. Such place-holders must be
ignored, when checking for cycles. A good example for this is JUnit 5:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=junit]
----

Any collection of slices can be used for cycle detection:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=set]
----

This can be written even shorter:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=enum]
----

Because each `Clazz` is a `Slice`, detecting class-cycles is as simple as:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=classes]
----

Even a `Map` can be used to pass the slices to check:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=map]
----

The `partitionByPackage()` method for a `Slice` returns a `Map` of package-names
to their corresponding package slices. Hence, all non-empty packages of a slice
can be listed like that:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=list]
----

To show the number of classes in each package use:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=size]
----

Any function that maps a `Clazz` to a string can be used to partition the
classes of a slice:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=top]
----

The implementation below return the top-level package name for spring-framework
classes:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=topm]
----

_Dessert_ comes with some pre-defined slice-partitioners. One of them is
`SlicePartitioners.HOST`. The host is the class that hosts all nested classes.
For a host or a class without nested classes the host is the class itself.
Thus, this partitioner produces slices where each slice contains a class
together with all its inner-classes:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CycleTest.java[tags=host]
----

=== Keeping vertical slices apart

Big applications, sometimes called _monolith_, are used by different stakeholders for
very different use-cases. Image some stamp-shop where a customer can buy stamps. The shop-owner
must be able to add new offerings and update prices. An office clerk handles the orders
and sends the stamps to customer. Once a month the shop-owner needs to get some statistics.
Hence, an application consists of verify different and hopefully independent parts
(typically there is no 1:1 mapping between use-case and part, that's why I name it part).
Normally the parts share components, the business model, services and other things,
and they are tied together within a common shell that provides authentication and
access control. Thus, the architecture of the application looks something like this:

[plantuml,vertical-slices,svg]
....
@startuml
package application
package part1
package part2
package part3
package commons

application <-- part1
application <-- part2
application <-- part3
part1 <-- commons
part2 <-- commons
part3 <-- commons
@enduml
....

In a clean design each part has its own module with explicit dependencies
to prevent any unintended cross-connections. But, this brings some overhead,
especially if there are many small parts. An alternative approach is to
use _dessert_:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/VerticalSlicesTest.java[tags=parts]
----

The doubly nested loop can be replaced by using _dessert's_ `CombinationUtils`:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/VerticalSlicesTest.java[tags=combinations]
----

=== Checking a layered architecture

The stamp-shop above is also an example for a layered architecture with 3 layers:

[plantuml,layers,svg]
....
@startuml
package application
package parts
package commons

application <-- parts
parts <-- commons
@enduml
....

_Dessert_ provides convenience methods to check layers:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/VerticalSlicesTest.java[tags=layered]
----

The test above will fail if _application_ uses _commons_. To relax this use:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/VerticalSlicesTest.java[tags=relaxed]
----

=== Detecting duplicates

Each JAR has its own directory structure, thus a class with the same fully qualified name
may appear in more than one JAR. The `ClassLoader` always uses the first matching class
on the classpath, but the order of the JARs on the classpath may vary on different systems.
Hence, your application may use the implementation of class A from jar X on one system
and the implementation from jar Y on other systems. If these two implementations behave
differently, then you have a problem.

To prevent duplicates in your application write a test as simple as:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/DuplicatesTest.java[tags=noDuplicates]
----

NOTE: Many JARs contain a `module-info` class in their root package. Make sure to ignore
this class when checking for duplicates.

Sometimes you cannot prevent all duplicates (i.e. if you're using Java 8), but at least you should
have a test that informs you if there are additional duplicates.

[source, java, indent=0]
----
include::{duplicates-sample-dir}/src/test/java/de/spricom/dessert/duplicates/ShowDuplicatesTest.java[tags=noAdditionalDuplicates]
----

The sample above prints all duplicate classes and the corresponding jars.

You may want to do some further investigations. To list all classes for which there are
binary differences in the .class file, you can use:

[source, java, indent=0]
----
include::{duplicates-sample-dir}/src/test/java/de/spricom/dessert/duplicates/ShowDuplicatesTest.java[tags=binary]
----

To list all classes for which there are API differences, you can use:

[source, java, indent=0]
----
include::{duplicates-sample-dir}/src/test/java/de/spricom/dessert/duplicates/ShowDuplicatesTest.java[tags=api]
----

=== Simulating refactorings

Sometimes a package cycle can be resolved by moving a class from one package to another.
Doing that may require many changes and -- as a side effect -- new cycles may be introduced.
Wouldn't it be nice if one could predict the effects of moving a class?

With _dessert_ you can use the `Slice` methods `minus` and `plus` to simulate
the removal of a `Clazz` from one slice and the addition to another:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/SimulatingRefactoringsTest.java[tags=simulate]
----

The sample shows: If one moved `SomeUtil` from `..stampshop.parts.part3` to
`..stampshop.application` that would introduce a package cycle.

<1> Create new Map<String, Slice> from Map<String, PackageSlice> to be able to replace a `PackageSlice`
by a `Slice`.
<2> Assign the package-name to the newly create `Slice` so that it looks like a `PackageSlice`
in the `AssertionError` message.
<3> This assertion will fail, because a package-cycle would be introduced by moving `SomeUtil`.

=== Defining a custom classpath

By default, the `Classpath` is based on the path defined by the _java.class.path_ system property.
For most use-cases that's what you want, but there might be circumstances where this is not suitable.
`Classpath` uses a `ClassResolver` to determine the locations it looks for classes.
`ClassResolver` has static factory methods for most common use cases, for example:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CustomClasspathTest.java[tags=customClasspath]
----

The code above defines a `Classpath` that contains only the _classes_ directories of the current class-path.

CAUTION: Never use different `Classpath` instances in a _dessert_ test. The result of `Slice` operations
and assertions is undefined if the slices originate from different `Classpath` instances and the
behaviour may change over time.

A  `Classpath`, that does not contain all classes used for an application, has some restrictions.
For example, assertions using name patterns do work:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CustomClasspathTest.java[tags=pattern]
----

NOTE: `Classpath` implements the `Slice` interfaces, thus `assertThatSlice` can be called
with `customClasspath`.

But assertions, that need access to the .class file, will fail:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CustomClasspathTest.java[tags=class]
----

The code above will throw:
----
java.lang.IllegalArgumentException: org.junit.jupiter.api.Test not found within this classpath.
----

To see all locations, where classes are searched for, you might use:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CustomClasspathTest.java[tags=slowDump]
----

The code above is very slow, because it iterates over all classes, rather use
`ClassResolver.getPath()`:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CustomClasspathTest.java[tags=fastDump]
----

To see all locations used by default you can use:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CustomClasspathTest.java[tags=dumpDefault]
----

The code above lists all locations where a `Classpath` instance, created with the default-constructor,
searches for classes.

You may even use the default `Classpath` to determine the location of .jar files, so that you
can build a custom `Classpath`:

[source, java, indent=0]
----
include::{sample-dir}/src/test/java/de/spricom/dessert/guide/CustomClasspathTest.java[tags=junitClasspath]
----
