== Release Notes

=== dessert-core-0.5.3

Bugfix-release:

- Return same URI as ClassLoader for JDK classes by removing modules prefix.

=== dessert-core-0.5.2

Minor additions and bugfixes:

- Assertions method aliases added for using plural in assertions.
- Alias `assertThatSlice` added for `dessert`.
- Bugfix: `isLayeredStrict` does not skip first slice anymore.
- Bugfix: Doesn't log warning for versioned duplicates in multi-release jars.
- Bugfix: Encoded URL's in within Manifest Class-Path entries will be resolved correctly.
- Javadocs added and typos fixed.
- Documentation: Tutorial replaced by practical guide.

=== dessert-core-0.5.1

Bugfixes and minor enhancements:

- JPMS detection fixed for Java 8
- Adds ClazzPredicates.DEPRECATED
- Static constructor methods os ClassResolver throw ResolveException instead of an IOException
- Javadocs added and typos fixed

=== dessert-core-0.5.0

This feature release primarily adds support for the JPMS, even for JDK 8 and older:

- Utilize information within module-info classes, to make sure only exported classes are used.
- Ready-to-use module definitions for the JDK that resemble the Java17 modules,
  to be used for older java versions
- Supports .class files up to Java 18 (inkl. sealed classes and records)
- Support multi-release jars
- Predicates for filtering by Annotations (for retention types class and runtime)
- API for nested classes
- Some utilities for combinations and dependency-closure
- Deprecated `Classpath` method `sliceOf(String...)` has been removed

=== dessert-core-0.4.3

Preparation for 0.5.0:

- https://github.com/hajo70/dessert-core/issues/4[Issue #4]: Adds entries from Class-Path header of Manifest files
- Improved `DefaultCycleRenderer` lists classes involved in cycle
- `SliceAssert` alias method `doesNotUse` for `usesNot` added
- `Classpath` method `sliceOf(String...)` deprecated (to be removed in 0.5.0)

=== dessert-core-0.4.2

Bugfix-release:

- The cycle detection algorithm ignores dependencies within the same slice, now.

=== dessert-core-0.4.1

Some minor changes:

- Duplicate .class files in JAR files won't cause an AssertionError.
- A `Clazz` created by `Classpath.asClazz(java.lang.Class<?>)` immediately contains all
  alternatives on the `Classpath`.
- `ClassPackage` internally uses `TreeMap` instead of `List` to lookup classes. This
  improves the performance if a package has many classes.
- Many Javadoc additions.

=== dessert-core-0.4.0

Starting with this release dessert will be available on Maven Central. Therefore, the maven coordinates
have been changed. The project has been renamed to dessert-core and everything that does not belong
to the core functionality (i.e. DuplicateFinder) has been deleted.

The most prominent changes are:

- New maven coordinates: de.spricom.dessert:dessert-core
- Removal of DuplicateFinder and corresponding traversal API
- Support for any Classfile-Format up to Java 15
- Multi-Release JARs don't cause an error (but version specific classes are ignored)
- API much simpler and more intuitive: SliceEntry renamed to Clazz,
  SliceContext renamed to Classpath and both implement Slice
- The Grouping-API has been replaced by simple maps and methods for partitioning
- Performant pattern-matching for class-names
- Many bugfixes, simplifications and preformance-improvements

=== Older Releases

See https://github.com/hajo70/dessert-core/releases[GitHub releases].