:sample-dir: C:\Code\git\dessert\dessert-site\dessert-sample

== User Documentation

=== Background

Dessert is a library to detect dependency violations. Hence it detects if there is something
that dependends on something else it should not. Therefore dessert needs means to
express what's meant be _something_, _something else_ and _should not depend on_.

Dessert checks dependencies between java classes. A class is represented by `Clazz`.
A `Clazz` stands for anything for which there is a separate .class file (interfaces,
annotation, enums, inner-classes, module specification or plain java class).

The `Clazz` is the smallest unit of granularity dessert can work with. The biggest
unit is the `Classpath`. The `Classpath` contains all classes within your application.

To specify dependency assertions you have to tear the `Classpath` down into smaller pieces.
Imagine the `Classpath` is a big cake you have slice down. Thus the most import concept
of _dessert_ is the `Slice`. The smallest `Slice` is a `Clazz` and the biggest `Slice` is
the `Classpath`.

=== Design Goals and Features

If you're considering to use _dessert_ you probably have problems with dependencies.
Hence the most important design goal was to not introduce any additional dependency
that might cause you a headache.

* No other dependencies but pure java
* Support a wide range of java versions an execution environments
* Easy and seamless integration with other testing or assertion frameworks
* Simple and intuitive API (motivated by [AssertJ](https://joel-costigliola.github.io/assertj/))
* Assertions should be robust against refactorings (no strings for class- or package names required)
* Compatibility to the https://docs.oracle.com/en/java/javase/15/docs/specs/man/jdeps.html[_jdeps_] utility.
* Focus on dependency assertions and nothing else
* Support for projects of any scale
* Speed

The design goals lead to these features:

* Supports any JDK from Java 6 to Java 15
* Has only dependencies to classes within the `java.base` module
* Annalyzes more than 10000 classes per second on a typical developer machine
  footnote:[See the https://github.com/hajo70/dessert-tests/blob/master/dessert-jdeps-tests/src/test/java/de/spricom/dessert/classfile/DessertPerformanceTest.java[dessert-tests] project for a corresponding performanc test.]
* Detects any dependency _jdeps_ detects.
  footnote:[This has been verified for more that 40000 classes. See https://github.com/hajo70/dessert-tests[dessert-tests] for details. Please open an issue if you encounter
  any class for which this is not true.] (This is not true the other way round,
  see the FAQ why this is so.)
* Performs the dependency analysis as late as possible to prevent any unnecessary analysis.
  Thus its safe to use on big projects with lots of dependencies.

=== The Slice

When using dessert you work most of the time with some `Slice` implementation. The following diagram
shows all such implementations provided by dessert:

[plantuml, slice-overview, svg]
....
include::{sample-dir}/target/docgen/slice-overview.puml[]
....

The most important `Slice` methods are `plus`, `minus`, and `slice` to create new slices from existing
ones. The `AbstractRootSlice` provides some convenience methods to work with packages. `packageOf` returns
a slice of all classes within one package (without sub-packages). `packageTreeOf' returns a slice of
all classes within a package, or a nested sub-package. Called on a `Root` these methods return only
classes within that root. A `Root` is a classes directory or a .jar file that belongs to the `Classpath`.
To get a `Root` you can use the `Classpath` method `rootOf`.

The `Classpath` methods `asClazz` and `sliceOf` can create slices for classes that are not on the
`Classpath` such as classes located in the java or javax packages or dependencies of some classes.
In such a case the `Classpath` uses the current `ClassLoader` to get the corresponding .class file.
If this does not work either, it creates a placeholder `Clazz` that contains only the classname.

The `slice` methods of `Classpath` do not necessarily return a slice that can be resolved to a concrete
set of classes. A slice may also be defined by a name-pattern or some predicate. For such a slice one
can use the `contains` method to check whether a `Clazz` belongs to it, thus the class fulfills
all predicates. But calling `getClazzes` will throw a `ResolveException`. This happens if the
`Classpath` contains none of the classes belonging to the slice. Internally _dessert_ works with such
predicate based slices as long as `getClazzes` has not been called, for performance reasons.

_Dessert_ has been optimized to resolve name-pattern very fast. Hence, it's a good practice to first
slice be name (or `packageOf`/`packageTreeOf`) then used predicates to slice-down the slices further.

`getDependencies` returns the dependencies of a slice and `uses` checks whether some other slice
contains one of these dependencies.

To add features to existing slices always extend `AbstractDelegateSlice`. The `named` method returns
one such extension that makes a slices' `toString` method return the name passed.

=== Name-Patterns
